# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2decf6fb300ce65e72dd87ab3b3298bc46083e0e8cdd70f324cf46c0ff320e8f62c7b2781db334828e6121d4a9d2ba6830fe08ecda3f68646b230142eb08e31

test:
  secret_key_base: c894e7cf98121142e04fbbb8ff623e09e67bfe2a499fb9515fd13d349cee913ed2309c692845b2534b809ccb8e9eacda74d0a7f5f79da71cdd5817d872d174a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
